package paq_vistas.ventas;

import paq_controladores.ventas.OyentesMultiplesVenta;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import paq_modelos.db.ModSQLVentas;
import paq_utilidades.ModVentanas;

public class PanelVentas extends javax.swing.JPanel {

    public PanelVentas() {
        this(new ModSQLVentas());
    }
    
    public PanelVentas(ModSQLVentas sqlVentas) {
        initComponents();
        sqlVentas.setDefaultModeloTablaVenta((DefaultTableModel) this.tb_ventas.getModel());
        addEventos(new OyentesMultiplesVenta(sqlVentas, this));
        sqlVentas.setTablaVentasProductos(tb_ventas);
        this.bt_cobrar.setEnabled(false);
    }
    
    public final void addEventos(OyentesMultiplesVenta oyente) {
        ModVentanas.getVentanaPadre().addKeyListener(oyente);
        this.tb_ventas.addKeyListener(oyente);
        this.tx_codigo.addKeyListener(oyente);
        this.bt_delproducto.addActionListener(oyente);
        this.bt_buscar.addActionListener(oyente);
        this.bt_cobrar.addActionListener(oyente);
        this.bt_checaprecio.addActionListener(oyente);
        this.tx_codigo.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentro = new javax.swing.JPanel();
        panelCentroFuncionesVentas = new javax.swing.JPanel();
        panelFuncionesCodigoBotones = new javax.swing.JPanel();
        panelCodigoDeBarras = new javax.swing.JPanel();
        et_codigo = new javax.swing.JLabel();
        tx_codigo = new javax.swing.JTextField();
        panelBotonesFunciones = new javax.swing.JPanel();
        bt_buscar = new javax.swing.JButton();
        bt_delproducto = new javax.swing.JButton();
        bt_checaprecio = new javax.swing.JButton();
        panelCentroTabla = new javax.swing.JPanel();
        panelTabla = new javax.swing.JScrollPane();
        tb_ventas = new javax.swing.JTable();
        panelSurCobrar = new javax.swing.JPanel();
        panelGridCobrar = new javax.swing.JPanel();
        panelTextoYBotones = new javax.swing.JPanel();
        et_numproductos = new javax.swing.JLabel();
        panelBotonCobrar = new javax.swing.JPanel();
        bt_cobrar = new javax.swing.JButton();
        panelMonto = new javax.swing.JPanel();
        et_monto = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        panelCentro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 24))); // NOI18N
        panelCentro.setLayout(new java.awt.BorderLayout());

        panelCentroFuncionesVentas.setLayout(new java.awt.BorderLayout());

        panelFuncionesCodigoBotones.setLayout(new java.awt.GridLayout(2, 0));

        panelCodigoDeBarras.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        et_codigo.setText("Codigo de Producto:");
        panelCodigoDeBarras.add(et_codigo);

        tx_codigo.setColumns(25);
        tx_codigo.setName("agregarProducto"); // NOI18N
        tx_codigo.setPreferredSize(new java.awt.Dimension(310, 40));
        panelCodigoDeBarras.add(tx_codigo);

        panelFuncionesCodigoBotones.add(panelCodigoDeBarras);

        panelBotonesFunciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        bt_buscar.setText("Buscar");
        bt_buscar.setName("bt_buscar"); // NOI18N
        bt_buscar.setPreferredSize(new java.awt.Dimension(209, 40));
        panelBotonesFunciones.add(bt_buscar);

        bt_delproducto.setText("Borrar Art.");
        bt_delproducto.setName("botonBorrar"); // NOI18N
        bt_delproducto.setPreferredSize(new java.awt.Dimension(209, 40));
        panelBotonesFunciones.add(bt_delproducto);

        bt_checaprecio.setText("Verificar Precio");
        bt_checaprecio.setName("botonVerificar"); // NOI18N
        bt_checaprecio.setPreferredSize(new java.awt.Dimension(209, 40));
        panelBotonesFunciones.add(bt_checaprecio);

        panelFuncionesCodigoBotones.add(panelBotonesFunciones);

        panelCentroFuncionesVentas.add(panelFuncionesCodigoBotones, java.awt.BorderLayout.CENTER);

        panelCentro.add(panelCentroFuncionesVentas, java.awt.BorderLayout.NORTH);

        panelCentroTabla.setLayout(new java.awt.BorderLayout());

        tb_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de Barras", "Descripción del Producto", "Precio Venta", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelTabla.setViewportView(tb_ventas);

        panelCentroTabla.add(panelTabla, java.awt.BorderLayout.CENTER);

        panelCentro.add(panelCentroTabla, java.awt.BorderLayout.CENTER);

        panelSurCobrar.setLayout(new java.awt.BorderLayout());

        panelGridCobrar.setLayout(new java.awt.BorderLayout());

        panelTextoYBotones.setLayout(new java.awt.BorderLayout());

        et_numproductos.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        et_numproductos.setText("0 Productos en la Venta Actual");
        panelTextoYBotones.add(et_numproductos, java.awt.BorderLayout.CENTER);

        panelBotonCobrar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        bt_cobrar.setText("Cobrar");
        bt_cobrar.setName("bt_cobrar"); // NOI18N
        bt_cobrar.setPreferredSize(new java.awt.Dimension(200, 70));
        panelBotonCobrar.add(bt_cobrar);

        panelTextoYBotones.add(panelBotonCobrar, java.awt.BorderLayout.EAST);
        panelBotonCobrar.getAccessibleContext().setAccessibleName("");

        panelGridCobrar.add(panelTextoYBotones, java.awt.BorderLayout.CENTER);

        panelMonto.setLayout(new java.awt.BorderLayout());

        et_monto.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        et_monto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        et_monto.setText("$0,00");
        et_monto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMonto.add(et_monto, java.awt.BorderLayout.CENTER);

        panelGridCobrar.add(panelMonto, java.awt.BorderLayout.EAST);

        panelSurCobrar.add(panelGridCobrar, java.awt.BorderLayout.CENTER);

        panelCentro.add(panelSurCobrar, java.awt.BorderLayout.SOUTH);

        add(panelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JPanel getPanelCentro() {
        return panelCentro;
    }
    
    public JTextField getCampoCodigoBarras() {
        return tx_codigo;
    }
    
    public javax.swing.JLabel getEtiquetaNumeroProductos() {
        return et_numproductos;
    }
    
    public javax.swing.JLabel getEtiquetaMonto() {
        return et_monto;
    }
    
    public javax.swing.JButton getBotonCobrar() {
        return bt_cobrar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_checaprecio;
    private javax.swing.JButton bt_cobrar;
    private javax.swing.JButton bt_delproducto;
    private javax.swing.JLabel et_codigo;
    private javax.swing.JLabel et_monto;
    private javax.swing.JLabel et_numproductos;
    private javax.swing.JPanel panelBotonCobrar;
    private javax.swing.JPanel panelBotonesFunciones;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelCentroFuncionesVentas;
    private javax.swing.JPanel panelCentroTabla;
    private javax.swing.JPanel panelCodigoDeBarras;
    private javax.swing.JPanel panelFuncionesCodigoBotones;
    private javax.swing.JPanel panelGridCobrar;
    private javax.swing.JPanel panelMonto;
    private javax.swing.JPanel panelSurCobrar;
    private javax.swing.JScrollPane panelTabla;
    private javax.swing.JPanel panelTextoYBotones;
    private javax.swing.JTable tb_ventas;
    private javax.swing.JTextField tx_codigo;
    // End of variables declaration//GEN-END:variables

}
